#!/usr/bin/env bash
# Utility script to check whether a Penumbra state dir exists,
# and exit non-zero if so. Useful to reuse throughout a variety
# of CI scripts for the Penumbra monorepo.
set -euo pipefail


# Fail fast if testnet dir exists, otherwise `cargo run ...` will block
# for a while, masking the error.
penumbra_devnet_home="${PENUMBRA_DEVNET_HOME:-$HOME/.penumbra}"
network_data_dir="${penumbra_devnet_home}/network_data"

if [[ -d "$network_data_dir" ]] ; then
    >&2 echo "ERROR: network data directory exists at $network_data_dir"
    >&2 echo "Not removing this directory automatically; to remove, run: pd network unsafe-reset-all"
    exit 1
fi
