// Code generated by gen-transfer-families; DO NOT EDIT.
// Manifest SHA256: f7b6cbc21cc4e1d9c9b7bcff854026db06fed922240ad3f56685347e047ea754
use anyhow::Result;
use ark_groth16::PreparedVerifyingKey;
use decaf377::{Bls12_377, Fq};
use penumbra_sdk_proof_params::batch::BatchItem;
use penumbra_sdk_shielded_pool::TransferFamilyId;

use crate::{
    backend::{AggregateBuildBackendProfile, AggregateVerificationProfile},
    srs::DevSrs,
    transcript::TransferTranscriptDigest,
};

/// Verifies a transfer-family aggregate proof and returns an
/// AggregateVerificationProfile for instrumentation.
///
/// "Unchecked" here does not bypass SnarkPack verification. It means the caller must
/// already have selected the correct transfer family, transcript domain, verifying key,
/// and padded public inputs before calling this helper.
///
/// Safe usage: internal validation and profiling paths after transfer-family routing and
/// aggregate input preparation have already succeeded.
///
/// Unsafe usage: calling this helper with mismatched family metadata, transcript domain,
/// or public inputs. That will still run cryptographic verification, but the result and
/// profiling data will not be meaningful for the intended family.
pub(crate) fn verify_transfer_family_aggregate_profiled_unchecked_generated(
    family_id: TransferFamilyId,
    pvk: &PreparedVerifyingKey<Bls12_377>,
    aggregate_proof_bytes: &[u8],
    padded_public_inputs: &[Vec<Fq>],
    srs: &DevSrs,
) -> Result<AggregateVerificationProfile> {
    match family_id {
        TransferFamilyId::OneByOne => {
            crate::backend::verify_with_digest_profiled::<
                TransferTranscriptDigest<{ TransferFamilyId::OneByOne.get() }>,
            >(pvk, aggregate_proof_bytes, padded_public_inputs, srs)
        }
        TransferFamilyId::OneByTwo => {
            crate::backend::verify_with_digest_profiled::<
                TransferTranscriptDigest<{ TransferFamilyId::OneByTwo.get() }>,
            >(pvk, aggregate_proof_bytes, padded_public_inputs, srs)
        }
        TransferFamilyId::TwoByOne => {
            crate::backend::verify_with_digest_profiled::<
                TransferTranscriptDigest<{ TransferFamilyId::TwoByOne.get() }>,
            >(pvk, aggregate_proof_bytes, padded_public_inputs, srs)
        }
        TransferFamilyId::TwoByTwo => {
            crate::backend::verify_with_digest_profiled::<
                TransferTranscriptDigest<{ TransferFamilyId::TwoByTwo.get() }>,
            >(pvk, aggregate_proof_bytes, padded_public_inputs, srs)
        }
        other => anyhow::bail!("unknown transfer family id {}", other.get()),
    }
}

pub(crate) fn aggregate_transfer_family_generated(
    family_id: TransferFamilyId,
    items: &[BatchItem],
    srs: &DevSrs,
) -> Result<Vec<u8>> {
    match family_id {
        TransferFamilyId::OneByOne => crate::backend::aggregate_with_digest::<
            TransferTranscriptDigest<{ TransferFamilyId::OneByOne.get() }>,
        >(items, srs),
        TransferFamilyId::OneByTwo => crate::backend::aggregate_with_digest::<
            TransferTranscriptDigest<{ TransferFamilyId::OneByTwo.get() }>,
        >(items, srs),
        TransferFamilyId::TwoByOne => crate::backend::aggregate_with_digest::<
            TransferTranscriptDigest<{ TransferFamilyId::TwoByOne.get() }>,
        >(items, srs),
        TransferFamilyId::TwoByTwo => crate::backend::aggregate_with_digest::<
            TransferTranscriptDigest<{ TransferFamilyId::TwoByTwo.get() }>,
        >(items, srs),
        other => anyhow::bail!("unknown transfer family id {}", other.get()),
    }
}

pub(crate) fn verify_transfer_family_aggregate_generated(
    family_id: TransferFamilyId,
    pvk: &PreparedVerifyingKey<Bls12_377>,
    aggregate_proof_bytes: &[u8],
    padded_public_inputs: &[Vec<Fq>],
    srs: &DevSrs,
) -> Result<bool> {
    match family_id {
        TransferFamilyId::OneByOne => {
            crate::backend::verify_with_digest::<
                TransferTranscriptDigest<{ TransferFamilyId::OneByOne.get() }>,
            >(pvk, aggregate_proof_bytes, padded_public_inputs, srs)
        }
        TransferFamilyId::OneByTwo => {
            crate::backend::verify_with_digest::<
                TransferTranscriptDigest<{ TransferFamilyId::OneByTwo.get() }>,
            >(pvk, aggregate_proof_bytes, padded_public_inputs, srs)
        }
        TransferFamilyId::TwoByOne => {
            crate::backend::verify_with_digest::<
                TransferTranscriptDigest<{ TransferFamilyId::TwoByOne.get() }>,
            >(pvk, aggregate_proof_bytes, padded_public_inputs, srs)
        }
        TransferFamilyId::TwoByTwo => {
            crate::backend::verify_with_digest::<
                TransferTranscriptDigest<{ TransferFamilyId::TwoByTwo.get() }>,
            >(pvk, aggregate_proof_bytes, padded_public_inputs, srs)
        }
        other => anyhow::bail!("unknown transfer family id {}", other.get()),
    }
}

pub(crate) fn aggregate_transfer_family_profiled_generated(
    family_id: TransferFamilyId,
    items: &[BatchItem],
    srs: &DevSrs,
) -> Result<(Vec<u8>, AggregateBuildBackendProfile)> {
    match family_id {
        TransferFamilyId::OneByOne => crate::backend::aggregate_with_digest_profiled::<
            TransferTranscriptDigest<{ TransferFamilyId::OneByOne.get() }>,
        >(items, srs),
        TransferFamilyId::OneByTwo => crate::backend::aggregate_with_digest_profiled::<
            TransferTranscriptDigest<{ TransferFamilyId::OneByTwo.get() }>,
        >(items, srs),
        TransferFamilyId::TwoByOne => crate::backend::aggregate_with_digest_profiled::<
            TransferTranscriptDigest<{ TransferFamilyId::TwoByOne.get() }>,
        >(items, srs),
        TransferFamilyId::TwoByTwo => crate::backend::aggregate_with_digest_profiled::<
            TransferTranscriptDigest<{ TransferFamilyId::TwoByTwo.get() }>,
        >(items, srs),
        other => anyhow::bail!("unknown transfer family id {}", other.get()),
    }
}
