// Code generated by gen-transfer-families; DO NOT EDIT.
// Manifest SHA256: f7b6cbc21cc4e1d9c9b7bcff854026db06fed922240ad3f56685347e047ea754
use anyhow::Error;

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, serde::Deserialize, serde::Serialize,
)]
#[serde(transparent)]
pub struct TransferFamilyId(pub u32);

#[allow(non_upper_case_globals)]
impl TransferFamilyId {
    pub const OneByOne: Self = Self(1);
    pub const OneByTwo: Self = Self(2);
    pub const TwoByOne: Self = Self(3);
    pub const TwoByTwo: Self = Self(4);

    pub const ALL: [Self; 4] = [
        Self::OneByOne,
        Self::OneByTwo,
        Self::TwoByOne,
        Self::TwoByTwo,
    ];

    pub const fn get(self) -> u32 {
        self.0
    }

    pub fn label(self) -> &'static str {
        self.spec().label
    }

    pub fn input_count(self) -> usize {
        self.spec().n_in
    }

    pub fn output_count(self) -> usize {
        self.spec().n_out
    }

    pub fn auth_sig_count(self) -> usize {
        self.input_count()
    }

    pub const fn proving_implemented(self) -> bool {
        let _ = self;
        true
    }

    pub const fn planner_enabled(self) -> bool {
        let _ = self;
        true
    }

    pub fn from_shape(inputs: usize, outputs: usize) -> Option<Self> {
        Self::ALL.into_iter().find(|family| {
            let spec = family.spec();
            spec.n_in == inputs && spec.n_out == outputs
        })
    }

    pub fn spec(self) -> &'static TransferFamilySpec {
        TRANSFER_FAMILY_SPECS
            .iter()
            .find(|spec| spec.id == self)
            .expect("unknown transfer family id")
    }
}

impl TryFrom<u32> for TransferFamilyId {
    type Error = Error;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        let family = Self(value);
        if TRANSFER_FAMILY_SPECS.iter().any(|spec| spec.id == family) {
            Ok(family)
        } else {
            Err(anyhow::anyhow!("unknown transfer family id {value}"))
        }
    }
}

impl From<TransferFamilyId> for u32 {
    fn from(value: TransferFamilyId) -> Self {
        value.0
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TransferFamilySpec {
    pub id: TransferFamilyId,
    pub label: &'static str,
    pub artifact_name: &'static str,
    pub n_in: usize,
    pub n_out: usize,
    pub statement_field_count: usize,
}

pub const TRANSFER_FAMILY_SPECS: [TransferFamilySpec; 4] = [
    TransferFamilySpec {
        id: TransferFamilyId::OneByOne,
        label: "transfer1x1",
        artifact_name: "transfer1x1",
        n_in: 1,
        n_out: 1,
        statement_field_count: crate::public_input_hash::transfer_statement_field_count(1, 1),
    },
    TransferFamilySpec {
        id: TransferFamilyId::OneByTwo,
        label: "transfer1x2",
        artifact_name: "transfer1x2",
        n_in: 1,
        n_out: 2,
        statement_field_count: crate::public_input_hash::transfer_statement_field_count(1, 2),
    },
    TransferFamilySpec {
        id: TransferFamilyId::TwoByOne,
        label: "transfer2x1",
        artifact_name: "transfer2x1",
        n_in: 2,
        n_out: 1,
        statement_field_count: crate::public_input_hash::transfer_statement_field_count(2, 1),
    },
    TransferFamilySpec {
        id: TransferFamilyId::TwoByTwo,
        label: "transfer2x2",
        artifact_name: "transfer2x2",
        n_in: 2,
        n_out: 2,
        statement_field_count: crate::public_input_hash::transfer_statement_field_count(2, 2),
    },
];
